services:
  db-scheune:
    image: postgres
    restart: always
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - ./sql-data.sql:/docker-entrypoint-initdb.d/sql-data.sql
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=scheune
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
